site_name: MkLorum
site_url: https://example.com/
docs_dir: doc

nav:
  - Quickstart: quickstart.md

theme:
  name: material
  locale: en
  features:
  - content.tabs.link

plugins:
  - include-markdown

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true